from datetime import datetime

from src.phase0_foundations.models import PulseReport


class DocRenderer:
    """
    Converts a PulseReport into Markdown suitable for Google Docs.
    Keep output ASCII-only to avoid rendering/encoding issues.
    """

    def render(self, report: PulseReport) -> str:
        anchor = self.generate_anchor(report.product, report.iso_week)
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        top = report.themes[:3]

        md: list[str] = []

        # Title + anchor
        md.append(
            f'## Weekly Pulse — {report.product} — {report.iso_week} <a name="{anchor}"></a>'
        )
        md.append(f"*Period: {report.period} | Reviews Analyzed: **{report.review_count}***")
        md.append("")
        md.append("---")
        md.append("")

        # Top themes summary
        md.append("### Top 3 Themes")
        for theme in top:
            md.append(f"- **{theme.name}**: {theme.description}")
        md.append("")

        # Customer Voice
        md.append("### Customer Voice")
        for theme in top:
            md.append(f"#### {theme.name}")
            for quote in theme.quotes[:3]:
                md.append(f'> "{quote}"')
        md.append("")

        # Actionable Insights
        md.append("### Actionable Insights")
        for theme in top:
            md.append(f"**Addressing {theme.name}:**")
            for idea in theme.action_ideas[:3]:
                md.append(f"- {idea}")
            md.append("")

        md.append("---")
        md.append(f"*Report generated by Product Review Agent on {now}*")

        return "\n".join(md)

    @staticmethod
    def generate_anchor(product: str, iso_week: str) -> str:
        return f"pulse-{product.lower()}-{iso_week.lower()}"

