"""
Direct PulseReport → Google Docs batchUpdate formatter.
Strict two-color Groww palette: #6C63FF (blue) and #00D09C (teal).
All paragraphs use NORMAL_TEXT to prevent Google Docs' named-heading
default spacing from pushing content to a second page.
"""
from typing import List, Dict, Any
from src.phase0_foundations.models import PulseReport

# ── Groww brand palette (RGB fractions 0–1) ───────────────────────────────────
_BLUE  = {'red': 0.424, 'green': 0.388, 'blue': 1.000}   # #6C63FF
_TEAL  = {'red': 0.000, 'green': 0.816, 'blue': 0.612}   # #00D09C
_DARK  = {'red': 0.102, 'green': 0.102, 'blue': 0.181}   # #1a1a2e
_BODY  = {'red': 0.294, 'green': 0.333, 'blue': 0.388}   # #4b5563
_GRAY  = {'red': 0.612, 'green': 0.643, 'blue': 0.690}   # #9ca3af
_QUOTE = {'red': 0.380, 'green': 0.380, 'blue': 0.380}   # #616161

_ACCENTS  = [_BLUE, _TEAL, _BLUE]   # per-theme accent cycle
_DIVIDER  = "─" * 64


def _tint(c: dict, w: float = 0.22) -> dict:
    """Blend colour toward white: w=1 → original, w=0 → white."""
    return {k: c[k] * w + (1 - w) for k in ('red', 'green', 'blue')}


class PulseDocFormatter:
    """
    Builds Google Docs batchUpdate requests for a visually branded,
    single-page Groww weekly pulse report.
    """

    def __init__(self, start_index: int = 1):
        self.idx = start_index
        self.req: List[Dict[str, Any]] = []

        # Tight margins — key for single-page fit
        self.req.append({
            "updateDocumentStyle": {
                "documentStyle": {
                    "marginTop":    {"magnitude": 20, "unit": "PT"},
                    "marginBottom": {"magnitude": 20, "unit": "PT"},
                    "marginLeft":   {"magnitude": 30, "unit": "PT"},
                    "marginRight":  {"magnitude": 30, "unit": "PT"},
                },
                "fields": "marginTop,marginBottom,marginLeft,marginRight"
            }
        })

    # ── public API ────────────────────────────────────────────────────────────

    def format(self, report: PulseReport) -> List[Dict[str, Any]]:
        top = report.themes[:3]

        # ── HEADER ─────────────────────────────────────────────────────────
        self._p("Weekly Pulse  ·  " + report.product,
                bold=True, color=_BLUE, size=20,
                sp_above=0, sp_below=2, ls=100)

        self._p(report.iso_week,
                bold=True, color=_TEAL, size=12,
                sp_above=0, sp_below=1, ls=100)

        self._p(f"{report.period}  ·  {report.review_count:,} reviews analysed",
                italic=True, color=_GRAY, size=10,
                sp_above=0, sp_below=2, ls=100)

        self._divider(_BLUE, sp_above=2, sp_below=2)

        # ── TOP THEMES ───────────────────────────────────────────────────
        self._label(f"TOP {len(top)} THEMES", color=_BLUE, sp_below=2)

        for i, theme in enumerate(top):
            acc = _ACCENTS[i]
            self._card_head(theme.name, accent=acc)
            self._body(theme.description, sp_below=2)

        self._divider(_TEAL, sp_above=2, sp_below=2)

        # ── CUSTOMER VOICE ─────────────────────────────────────────────────
        self._label("CUSTOMER VOICE", color=_TEAL, sp_below=2)

        for i, theme in enumerate(top):
            acc = _ACCENTS[i]
            self._subhead(theme.name, accent=acc, sp_above=2, sp_below=1)
            
            # Deduplicate quotes preserving order
            seen = set()
            unique_quotes = []
            for q in theme.quotes:
                q_clean = q.strip().strip('"').strip("'")
                q_lower = q_clean.lower()
                if q_lower not in seen:
                    seen.add(q_lower)
                    unique_quotes.append(q_clean)
                    
            for q in unique_quotes[:3]:
                self._quote(q)

        self._divider(_BLUE, sp_above=2, sp_below=2)

        # ── ACTIONABLE INSIGHTS ────────────────────────────────────────────
        self._label("ACTIONABLE INSIGHTS", color=_BLUE, sp_below=2)

        for i, theme in enumerate(top):
            acc = _ACCENTS[i]
            self._subhead(f"Addressing {theme.name}",
                          accent=acc, italic=True, sp_above=2, sp_below=1)
            for idea in theme.action_ideas[:5]:
                self._bullet(idea, accent=acc)

        self._divider(_TEAL, sp_above=2, sp_below=2)

        # ── FOOTER ─────────────────────────────────────────────────────────
        ts = report.generated_at.strftime("%Y-%m-%d %H:%M:%S")
        self._p(f"Report generated by Product Review Agent on {ts}",
                italic=True, color=_GRAY, size=9,
                sp_above=0, sp_below=0, ls=100)

        # Remove the trailing \n so Google Docs doesn't create a blank page 2
        if self.idx > 1:
            self.req.append({
                "deleteContentRange": {
                    "range": {"startIndex": self.idx - 1, "endIndex": self.idx}
                }
            })

        return self.req

    # ── element renderers ─────────────────────────────────────────────────────

    def _label(self, text: str, color: dict, sp_below: float):
        """Uppercase section overline — NORMAL_TEXT, bold colored."""
        self._p(text, bold=True, color=color, size=14,
                sp_above=0, sp_below=sp_below, ls=100)

    def _card_head(self, text: str, accent: dict):
        """Theme name with a coloured left border for a card-like effect."""
        s = self.idx
        self._ins(text + "\n")
        e = self.idx
        self._ts(s, e, bold=True, color=accent, size=12)
        self._ps(s, e,
                 sp_above=2, sp_below=1, ls=100,
                 indent=10, border_color=accent, border_pt=2.5)

    def _body(self, text: str, sp_below: float = 4):
        """Description text indented under the card border."""
        s = self.idx
        self._ins(text + "\n")
        e = self.idx
        self._ts(s, e, color=_BODY, size=10)
        self._ps(s, e, sp_above=1, sp_below=sp_below, ls=105, indent=12)

    def _subhead(self, text: str, accent: dict, italic=False,
                 sp_above: float = 2, sp_below: float = 1):
        self._p(text, bold=True, italic=italic, color=accent, size=12,
                sp_above=sp_above, sp_below=sp_below, ls=100)

    def _quote(self, text: str):
        s = self.idx
        self._ins(f"“{text}”\n")
        e = self.idx
        self._ts(s, e, italic=True, color=_QUOTE, size=10)
        self._ps(s, e, sp_above=0, sp_below=0, ls=100, indent=12)

    def _bullet(self, text: str, accent: dict):
        s = self.idx
        self._ins("• ")
        mid = self.idx
        self._ins(text + "\n")
        e = self.idx
        if mid > s:
            self._ts(s, mid, bold=True, color=accent, size=10)
        if e > mid:
            self._ts(mid, e, color=_BODY, size=10)
        self._ps(s, e, sp_above=0, sp_below=0, ls=100, indent=6)

    def _divider(self, color: dict, sp_above: float = 4, sp_below: float = 4):
        s = self.idx
        self._ins(_DIVIDER + "\n")
        e = self.idx
        self._ts(s, e, color=_tint(color, 0.25), size=4)
        self._ps(s, e, sp_above=sp_above, sp_below=sp_below, ls=100)

    # ── generic paragraph helper ──────────────────────────────────────────────

    def _p(self, text: str, bold=False, italic=False, color=None, size: float = 8,
           sp_above: float = 0, sp_below: float = 2, ls: float = 110,
           indent: float = 0):
        s = self.idx
        self._ins(text + "\n")
        e = self.idx
        self._ts(s, e, bold=bold, italic=italic, color=color or _BODY, size=size)
        self._ps(s, e, sp_above=sp_above, sp_below=sp_below, ls=ls, indent=indent)

    # ── primitives ────────────────────────────────────────────────────────────

    def _ins(self, text: str):
        if not text:
            return
        import emoji
        text = emoji.replace_emoji(text, replace='')
        self.req.append({
            "insertText": {"location": {"index": self.idx}, "text": text}
        })
        self.idx += len(text)

    def _ts(self, start: int, end: int, bold=False, italic=False,
            color=None, size: float = 8):
        if start >= end:
            return
        self.req.append({
            "updateTextStyle": {
                "range": {"startIndex": start, "endIndex": end},
                "textStyle": {
                    "bold": bold,
                    "italic": italic,
                    "fontSize": {"magnitude": size, "unit": "PT"},
                    "foregroundColor": {"color": {"rgbColor": color or _BODY}},
                },
                "fields": "bold,italic,fontSize,foregroundColor"
            }
        })

    def _ps(self, start: int, end: int,
            sp_above: float = 0, sp_below: float = 2, ls: float = 110,
            indent: float = 0, border_color: dict = None, border_pt: float = 0):
        ps: dict = {
            "spaceAbove": {"magnitude": sp_above, "unit": "PT"},
            "spaceBelow": {"magnitude": sp_below, "unit": "PT"},
            "lineSpacing": ls,
        }
        fields = "spaceAbove,spaceBelow,lineSpacing"

        if indent > 0:
            ps["indentStart"]     = {"magnitude": indent, "unit": "PT"}
            ps["indentFirstLine"] = {"magnitude": indent, "unit": "PT"}
            fields += ",indentStart,indentFirstLine"

        if border_color and border_pt > 0:
            ps["borderLeft"] = {
                "color": {"color": {"rgbColor": border_color}},
                "width": {"magnitude": border_pt, "unit": "PT"},
                "dashStyle": "SOLID",
                "padding": {"magnitude": 5, "unit": "PT"}
            }
            fields += ",borderLeft"

        self.req.append({
            "updateParagraphStyle": {
                "range": {"startIndex": start, "endIndex": end},
                "paragraphStyle": ps,
                "fields": fields
            }
        })
